version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:management
    container_name: myrabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


networks:
  my-network:
    driver: bridge
